---
# tasks file for role
- name: include tasks
  block:
    - assert:
        that:
          - ansible_os_family is defined
          - ansible_os_family == 'RedHat'
    - include_tasks: "{{ ansible_os_family | lower }}-pre.yml"
    - include_tasks: "{{ ansible_os_family | lower }}-docker.yml"
  rescue:
    - debug:
        msg: "{{ ansible_os_family }} is not supported for this role (yet)"
