---
##
#
##
- name: docker | add gpg key
  become: true
  rpm_key:
    key: "{{ docker_repo_key }}"
    state: present

- name: docker | add main repo
  become: true
  get_url:
    url: "{{ docker_repo_url }}"
    dest: '/etc/yum.repos.d/docker-ce.repo'
    owner: root
    group: root
    mode: 0644

- name: docker | configure edge repo
  become: true
  ini_file:
    dest: '/etc/yum.repos.d/docker-ce.repo'
    section: 'docker-ce-edge'
    option: enabled
    value: "{{ docker_edge_enable }}"

- name: docker | configure test repo
  become: true
  ini_file:
    dest: '/etc/yum.repos.d/docker-ce.repo'
    section: 'docker-ce-test'
    option: enabled
    value: "{{ docker_test_enable }}"

- name: docker | main install
  become: true
  yum:
    name: docker-ce
    state: latest
  notify: docker installed

- meta: flush_handlers

- name: docker | install pip modules
  become: true
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker
    - docker-compose
